# Generated by Django 5.2 on 2025-04-18 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_event_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='event_info',
            name='attending',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event_info',
            name='room_num',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='event_info',
            name='time_zone',
            field=models.CharField(default='', max_length=35),
        ),
        migrations.AlterField(
            model_name='event_info',
            name='city',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='event_info',
            name='date',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='event_info',
            name='description',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='event_info',
            name='end_time',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='event_info',
            name='host',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='event_info',
            name='latitude',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='event_info',
            name='longitude',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='event_info',
            name='start_time',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='event_info',
            name='state',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='event_info',
            name='street',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='event_info',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='event_info',
            name='url',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='event_info',
            name='zipcode',
            field=models.CharField(default='', max_length=10),
        ),
    ]
