# Generated by Django 5.2 on 2025-04-19 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_attending_event_info_attendees_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_info',
            name='id',
        ),
        migrations.AlterField(
            model_name='user_info',
            name='username',
            field=models.CharField(max_length=48, primary_key=True, serialize=False),
        ),
    ]
