# Generated by Django 5.2 on 2025-04-19 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_event_info_created_at_event_info_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_info',
            name='latitude',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='event_info',
            name='longitude',
            field=models.IntegerField(default=0),
        ),
    ]
