# Generated by Django 5.2 on 2025-04-20 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_event_latitude_event_longitude"),
        ("api", "0009_alter_user_info_password"),
    ]

    operations = []
