# Generated by Django 5.2 on 2025-04-21 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_merge_20250420_1558"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Event",
        ),
    ]
