# Generated by Django 5.2 on 2025-04-21 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_delete_event"),
    ]

    operations = [
        migrations.AddField(
            model_name="event_info",
            name="creator",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events",
                to="api.user_info",
            ),
        ),
    ]
