# Generated by Django 5.2 on 2025-04-22 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_delete_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event_info',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='event_images/'),
        ),
        migrations.AddField(
            model_name='user_info',
            name='pfp_url',
            field=models.ImageField(blank=True, default='pfps/default.jpg', null=True, upload_to='pfps/'),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='email',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
