# Generated by Django 5.2 on 2025-04-22 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_event_info_image_url_user_info_pfp_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event_info',
            name='saved_by',
            field=models.ManyToManyField(related_name='saved_events', to='api.user_info'),
        ),
        migrations.RemoveField(
            model_name='event_info',
            name='attendees',
        ),
        migrations.AlterField(
            model_name='event_info',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events_hosted', to='api.user_info'),
        ),
        migrations.AddField(
            model_name='event_info',
            name='attendees',
            field=models.ManyToManyField(blank=True, related_name='events_attending', to='api.user_info'),
        ),
    ]
