# Generated by Django 5.2 on 2025-04-22 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_event_info_saved_by_remove_event_info_attendees_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_info',
            name='image_url',
            field=models.ImageField(blank=True, default='event_images/default.jpg', null=True, upload_to='event_images/'),
        ),
        migrations.AlterField(
            model_name='event_info',
            name='saved_by',
            field=models.ManyToManyField(blank=True, related_name='saved_events', to='api.user_info'),
        ),
    ]
